export const CACHE_CATEGORIES = 'CATEGORIES';
export const CACHE_SUB_CATEGORIES = 'SUB_CATEGORIES';
export const CACHE_PRODUCTS = 'PRODUCTS';
export const CACHE_BANNERS = 'BANNERS';
export const CACHE_STOCKS = 'STOCKS';
export const CACHE_COMMENTS = 'COMMENTS';
export const CACHE_TICKETS = 'TICKETS';
